observe:
  hive:
    enabled: true

    storage:
      console:
        enabled: false
      file:
        enabled: true
      elasticsearch:
        enabled: true
        hosts: http://localhost:9200
        index-pattern: "app-logs-{date}"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
