spring:
  application:
    name: observe hive starter

observe:
  hive:
    enabled: true
    adapters:
      logback:
        enabled: true
      log4j2:
        enabled: true
    storage:
      console:
        enabled: true
      file:
        enabled: true
      elasticsearch:
        enabled: true
        hosts: http://localhost:9200
        index-pattern: "app-logs-{date}"
